version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: qlikuser
      POSTGRES_PASSWORD: qlikpassword
      POSTGRES_DB: qlikdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      FLASK_ENV: development

volumes:
  postgres_data:
