"""Initial migration.

Revision ID: f23449e4a4b9
Revises: be14043056d1
Create Date: 2023-09-10 17:09:35.004028

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f23449e4a4b9'
down_revision = 'be14043056d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qlik_space', sa.Column('meta', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('qlik_space', sa.Column('links', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qlik_space', 'links')
    op.drop_column('qlik_space', 'meta')
    # ### end Alembic commands ###
