"""Initial migration.

Revision ID: fbaa1c17d5a4
Revises: 
Create Date: 2023-08-19 13:23:25.001238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbaa1c17d5a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assigned_group',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assigned_role',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.Column('level', sa.String(length=255), nullable=True),
    sa.Column('permissions', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qlik_app',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('usage', sa.String(length=50), nullable=True),
    sa.Column('ownerId', sa.String(length=255), nullable=True),
    sa.Column('encrypted', sa.Boolean(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.Column('thumbnail', sa.String(length=255), nullable=True),
    sa.Column('createdDate', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('originAppId', sa.String(length=255), nullable=True),
    sa.Column('publishTime', sa.String(length=255), nullable=True),
    sa.Column('dynamicColor', sa.String(length=50), nullable=True),
    sa.Column('modifiedDate', sa.String(length=255), nullable=True),
    sa.Column('lastReloadTime', sa.String(length=255), nullable=True),
    sa.Column('hasSectionAccess', sa.Boolean(), nullable=True),
    sa.Column('isDirectQueryMode', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qlik_user',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('tenantId', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('lastUpdated', sa.DateTime(), nullable=True),
    sa.Column('qlik_app_link', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reload_task',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('appId', sa.String(length=255), nullable=False),
    sa.Column('partial', sa.Boolean(), nullable=True),
    sa.Column('timeZone', sa.String(length=255), nullable=True),
    sa.Column('autoReload', sa.Boolean(), nullable=True),
    sa.Column('recurrence', sa.PickleType(), nullable=True),
    sa.Column('endDateTime', sa.DateTime(), nullable=True),
    sa.Column('startDateTime', sa.DateTime(), nullable=True),
    sa.Column('autoReloadPartial', sa.Boolean(), nullable=True),
    sa.Column('log', sa.Text(), nullable=True),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('userId', sa.String(length=255), nullable=False),
    sa.Column('spaceId', sa.String(length=255), nullable=True),
    sa.Column('tenantId', sa.String(length=255), nullable=True),
    sa.Column('fortressId', sa.String(length=255), nullable=True),
    sa.Column('lastExecutionTime', sa.DateTime(), nullable=True),
    sa.Column('nextExecutionTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_group_association',
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('group_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['assigned_group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['qlik_user.id'], )
    )
    op.create_table('user_role_association',
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('role_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['assigned_role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['qlik_user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_role_association')
    op.drop_table('user_group_association')
    op.drop_table('reload_task')
    op.drop_table('qlik_user')
    op.drop_table('qlik_app')
    op.drop_table('assigned_role')
    op.drop_table('assigned_group')
    # ### end Alembic commands ###
